name: codecheck

on:
  push:
    branches:
      - release-3.6.8-app
  pull_request:
    branches:
      - release-3.6.8-app

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup pnpm
        run: |
          npm --version
          npm install pnpm -g
          pnpm --version

      - name: pnpm install
        run: pnpm install --no-frozen-lockfil
               
      - name: lint
        run: pnpm lint

      - name: build for taro-helper
        working-directory: ./packages/taro-helper
        run: pnpm build
        
      - name: build for taro-components-mpharmony
        working-directory: ./packages/taro-components
        run: pnpm build
      
      - name: build
        run: pnpm build
        
      - name: test
        run: pnpm test
        env:
          CI: true
     
